# Generated by Django 4.1 on 2022-09-21 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='place',
            fields=[
                ('name', models.CharField(max_length=20, null=None, primary_key=True, serialize=False)),
                ('phone_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mgr_name', models.CharField(max_length=20)),
                ('mgr_dob', models.CharField(max_length=8)),
                ('work_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tt1.place')),
            ],
        ),
    ]
